github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-service-common
      branch: 7.0.x
      useSinglePullRequest: true
    - name: activiti-cloud-connectors
      branch: 7.0.x
      useSinglePullRequest: true
    - name: activiti-cloud-query-service
      branch: 7.0.x
      useSinglePullRequest: true
    - name: activiti-cloud-org-service
      branch: 7.0.x
      useSinglePullRequest: true
    - name: activiti-cloud-runtime-bundle-service
      branch: 7.0.x
      useSinglePullRequest: true
    - name: activiti-cloud-audit-service
      branch: 7.0.x
      useSinglePullRequest: true
    - name: activiti-cloud-api
      branch: 7.0.x
      useSinglePullRequest: true
    - name: activiti-cloud-process-model-service
      branch: 7.0.x
      useSinglePullRequest: true
    - name: activiti-cloud-app-service
      branch: 7.0.x
      useSinglePullRequest: true
    - name: activiti-cloud-notifications-service-graphql
      branch: 7.0.x
      useSinglePullRequest: true
    - name: activiti-cloud-dependencies
      branch: 7.0.x
      useSinglePullRequest: true
    - name: activiti-cloud-acceptance-tests
      branch: 7.0.x
      useSinglePullRequest: true
